const NETSCAPE_HEADER = [
  '# Netscape HTTP Cookie File',
  '# This file was generated by Nora. Edit at your own risk.',
  '',
].join('\n')

export function formatCookiesTxt(cookieHeader: string, url: string) {
  const target = new URL(url)
  const domain = target.hostname
  const secure = target.protocol === 'https:' ? 'TRUE' : 'FALSE'
  const rows = cookieHeader
    .split(';')
    .map((item) => item.trim())
    .filter(Boolean)
    .flatMap((item) => {
      const separator = item.indexOf('=')
      if (separator <= 0) return []

      const name = item.slice(0, separator).trim().replace(/[\t\r\n]/g, '')
      const value = item.slice(separator + 1).replace(/[\t\r\n]/g, '')
      if (!name) return []

      return [`${domain}\tFALSE\t/\t${secure}\t0\t${name}\t${value}`]
    })

  return rows.length ? `${NETSCAPE_HEADER}${rows.join('\n')}\n` : ''
}
